import * as animations from './animations';

export const CHARACTERS = [
  {
    id: 2,
    name: 'Char 2',
    image: '/images/character2.png',
    anim: animations.Char2Animations,
    description: 'Character 2 description',
  },
  {
    id: 3,
    name: 'Char 3',
    image: '/images/character3.png',
    anim: animations.Char3Animations,
    description: 'Character 3 description',
  },
  {
    id: 4,
    name: 'Char 4',
    image: '/images/character4.png',
    anim: animations.Char4Animations,
    description: 'Character 4 description',
  },
  {
    id: 1,
    name: 'Alise',
    anim: animations.AliseAnimations,
    description: 'Character 1 description',
  },
  {
    id: 5,
    name: 'Char 5',
    image: '/images/character5.png',
    anim: animations.Char5Animations,
    description: 'Character 5 description',
  },
  {
    id: 6,
    name: 'Char 6',
    image: '/images/character5.png',
    anim: animations.Char6Animations,
    description: 'Character 5 description',
  },
  {
    id: 7,
    name: 'Char 7',
    image: '/images/character5.png',
    anim: animations.Char7Animations,
    description: 'Character 5 description',
  },
];

export const SOUNDS = [
  { id: 0, name: 'beat', path: '/sounds/beat1.mp3', color: '#e8cab5' },
  { id: 1, name: 'beat3', path: '/sounds/beat3.mp3', color: '#ffb7ab' },
  { id: 2, name: 'choir', path: '/sounds/choir.mp3', color: '#a9cdcf' },
  { id: 3, name: 'goat', path: '/sounds/goat.mp3', color: '#f7dcab' },
  { id: 4, name: 'laugh', path: '/sounds/laugh.mp3', color: '#d4b66c' },
  { id: 5, name: 'cry', path: '/sounds/cry.mp3', color: '#ffee90' },
  { id: 6, name: 'laugh2', path: '/sounds/laugh2.mp3', color: '#f5aed1' },
  { id: 7, name: 'beat2', path: '/sounds/beat2.mp3', color: '#a2ffb3' },
  { id: 8, name: 'giggle', path: '/sounds/giggle.mp3', color: '#c28cc2' },
  { id: 9, name: 'laugh3', path: '/sounds/laugh3.mp3', color: '#4682B4' },
  { id: 10, name: 'cow', path: '/sounds/cow.mp3', color: '#ff91cb' },
  { id: 11, name: 'horror', path: '/sounds/horror.mp3', color: '#00FFFF' },
  { id: 12, name: 'monks', path: '/sounds/monks.mp3', color: '#cc8181' },
  { id: 13, name: 'applause', path: '/sounds/applause.mp3', color: '#ff8063' },
  { id: 14, name: 'christmas', path: '/sounds/christmas.mp3', color: '#a4b5ff' },
  { id: 15, name: 'trombone', path: '/sounds/trombone.mp3', color: '#d0ebb6' },
  { id: 16, name: 'violins', path: '/sounds/violins.mp3', color: '#d596a2' },
  { id: 17, name: 'polyphon', path: '/sounds/polyphon.mp3', color: '#a5d7a5' },
  { id: 18, name: 'guitar', path: '/sounds/guitar.mp3', color: '#efa5a5' },
  { id: 19, name: 'drums1', path: '/sounds/drums1.mp3', color: '#b8b1dc' },
  { id: 20, name: 'drums2', path: '/sounds/drums2.mp3', color: '#FFDAB9' },
];
