export const characters = [
  {
    id: 1,
    name: 'Char 1',
    image: '/images/character1.png',
    description: 'Character 1 description',
  },
  {
    id: 2,
    name: 'Char 2',
    image: '/images/character2.png',
    description: 'Character 2 description',
  },
  {
    id: 3,
    name: 'Char 3',
    image: '/images/character3.png',
    description: 'Character 3 description',
  },
  {
    id: 4,
    name: 'Char 4',
    image: '/images/character4.png',
    description: 'Character 4 description',
  },
  {
    id: 5,
    name: 'Char 5',
    image: '/images/character5.png',
    description: 'Character 5 description',
  },
  {
    id: 6,
    name: 'Char 6',
    image: '/images/character6.png',
    description: 'Character 6 description',
  },
  {
    id: 7,
    name: 'Char 7',
    image: '/images/character7.png',
    description: 'Character 7 description',
  },
  {
    id: 8,
    name: 'Char 8',
    image: '/images/character8.png',
    description: 'Character 8 description',
  },
];

export const soundFiles = [
  { id: 0, name: 'Beat1', path: '/sounds/beat1.mp3', color: '#e8cab5' },
  { id: 1, name: 'Beat2', path: '/sounds/beat2.mp3', color: '#a2ffb3' },
  { id: 2, name: 'Beat3', path: '/sounds/beat3.mp3', color: '#ffb7ab' },
  { id: 3, name: 'Choir', path: '/sounds/choir.mp3', color: '#a9cdcf' },
  { id: 4, name: 'Goat', path: '/sounds/goat.mp3', color: '#f7dcab' },
  { id: 5, name: 'Laugh', path: '/sounds/laugh.mp3', color: '#d4b66c' },
  { id: 6, name: 'Cry', path: '/sounds/cry.mp3', color: '#ffee90' },
  { id: 7, name: 'Laugh2', path: '/sounds/laugh2.mp3', color: '#f5aed1' },
  { id: 8, name: 'Giggle', path: '/sounds/giggle.mp3', color: '#c28cc2' },
  { id: 9, name: 'Laugh3', path: '/sounds/laugh3.mp3', color: '#4682B4' },
  { id: 10, name: 'Cow', path: '/sounds/cow.mp3', color: '#ff91cb' },
  { id: 11, name: 'Horror', path: '/sounds/horror.mp3', color: '#00FFFF' },
  { id: 12, name: 'Monks', path: '/sounds/monks.mp3', color: '#cc8181' },
  { id: 13, name: 'Applause', path: '/sounds/applause.mp3', color: '#ff8063' },
  { id: 14, name: 'Christmas', path: '/sounds/christmas.mp3', color: '#a4b5ff' },
  { id: 15, name: 'Trombone', path: '/sounds/trombone.mp3', color: '#d0ebb6' },
  { id: 16, name: 'Violins', path: '/sounds/violins.mp3', color: '#d596a2' },
  { id: 17, name: 'Polyphon', path: '/sounds/polyphon.mp3', color: '#a5d7a5' },
  { id: 18, name: 'Guitar', path: '/sounds/guitar.mp3', color: '#efa5a5' },
  { id: 19, name: 'Drums2', path: '/sounds/drums2.mp3', color: '#FFDAB9' },
  { id: 20, name: 'Drums1', path: '/sounds/drums1.mp3', color: '#b8b1dc' },
];
